"""Agent API 配置。"""

from agent.env_utils import (
    AGENT_API_PORT,
    MONGODB_CHECKPOINT_COLLECTION,
    MONGODB_DB_NAME,
    MONGODB_URI,
)

API_TITLE = "DocClaw Agent API"
API_VERSION = "0.1.0"
API_DESCRIPTION = "DocClaw DeepAgents Harness 对话 API"
AGENT_API_PORT = AGENT_API_PORT
MONGODB_URI = MONGODB_URI
MONGODB_DB_NAME = MONGODB_DB_NAME
MONGODB_CHECKPOINT_COLLECTION = MONGODB_CHECKPOINT_COLLECTION
