"""MCP Server 配置。"""

from agent.env_utils import MCP_HOST, MCP_PATH, MCP_PORT, MEDICAL_API_BASE_URL

MEDICAL_API_BASE = MEDICAL_API_BASE_URL
MCP_HOST = MCP_HOST
MCP_PORT = MCP_PORT
MCP_PATH = MCP_PATH
