/*
 * Copyright 2026 Elva LaoBai Contributors
 * Licensed under the Apache License, Version 2.0.
 */
package com.elva.laobai.forms

import android.content.Context
import android.util.Log
import com.elva.laobai.ElvaTtsManager
import com.elva.laobai.memory.LocalUserMemory
import com.elva.laobai.models.FormFieldDef
import com.elva.laobai.models.FormTemplate
import com.elva.laobai.models.FormTemplateMatch
import com.elva.laobai.models.NextAction
import com.elva.laobai.models.NextAction.ActionType
import com.elva.laobai.models.NextAction.RiskLevel
import com.elva.laobai.models.ScreenObservation

/**
 * Form Fill Engine — builds and manages the form-filling action sequence
 * for the always-on form filling assistant (Case 1).
 *
 * Flow:
 * 1. Template matched → ask user if they want help filling
 * 2. User confirms → read authorized fields from LocalUserMemory
 * 3. Build NextAction sequence for each field (type text)
 * 4. Stop before any blockedTarget (submit/payment/otp/authorization)
 *
 * SECURITY:
 * - Never auto-fills ID card, OTP, verification code fields
 * - Never auto-clicks submit/pay/authorize buttons
 * - Each field fill is announced via TTS
 * - Requires user confirmation before starting
 */
object FormFillEngine {
    private const val TAG = "FormFillEngine"

    /**
     * State of the form filling process.
     */
    data class FillState(
        val templateId: String? = null,
        val templateName: String? = null,
        val totalFields: Int = 0,
        val filledFields: Int = 0,
        val currentFieldLabel: String? = null,
        val isActive: Boolean = false,
        val isPaused: Boolean = false,
        val stoppedReason: String? = null,
    )

    private var currentState = FillState()

    /** Cache of actions generated by beginFill(). Rebuilt on each fill. */
    private var fillActions: List<NextAction> = emptyList()
    private var fillActionIndex: Int = 0

    /**
     * Check if the screen matches a template and prompt the user.
     * Called from AlwaysOnSentinel during passive scan.
     *
     * @param match The matched form template result.
     * @return The voice prompt NextAction to speak to the user.
     */
    fun checkAndPrompt(match: FormTemplateMatch): NextAction {
        val template = match.template ?: return NextAction(
            action = ActionType.SPEAK_ONLY,
            targetDescription = "no_match",
            voicePrompt = "",
            explanation = "No template",
            riskLevel = RiskLevel.ZERO,
            source = "form_engine",
        )

        val templateName = template.displayName
        val voicePrompt = "我看到这是一个${templateName}，要不要我帮您填写常用信息？"

        Log.d(TAG, "Prompting for template: ${template.templateId}")

        return NextAction(
            action = ActionType.ASK_CONFIRMATION,
            targetDescription = "form_fill_prompt_${template.templateId}",
            voicePrompt = voicePrompt,
            explanation = "检测到${templateName}页面，询问是否需辅助填写",
            riskLevel = RiskLevel.LOW,
            source = "form_engine",
        )
    }

    /**
     * Begin filling the form — generates the full action sequence.
     * Must only be called after user confirms they want help.
     *
     * @param template The matched form template.
     * @param observation The current screen observation (to verify field presence).
     * @return List of NextActions to execute sequentially.
     */
    fun beginFill(
        template: FormTemplate,
        observation: ScreenObservation?,
    ): List<NextAction> {
        val actions = mutableListOf<NextAction>()

        // Announce start
        actions.add(NextAction(
            action = ActionType.SPEAK_ONLY,
            targetDescription = "fill_start",
            voicePrompt = "好的，老白来帮您填写${template.displayName}，您看着就行~",
            explanation = "开始填写表单",
            riskLevel = RiskLevel.ZERO,
            source = "form_engine",
        ))

        // Build fill actions for each required field
        for (fieldDef in template.requiredFields) {
            val memoryValue = getMemoryValue(fieldDef)
            if (memoryValue != null && memoryValue.isNotBlank()) {
                actions.add(NextAction(
                    action = ActionType.TYPE_TEXT,
                    targetDescription = fieldDef.uiLabel,
                    value = memoryValue,
                    voicePrompt = "正在帮您填${fieldDef.uiLabel}：${memoryValue}",
                    explanation = "填写字段: ${fieldDef.uiLabel}",
                    riskLevel = RiskLevel.MEDIUM,
                    source = "form_engine",
                ))
            } else {
                // Field not available in memory — skip and notify
                Log.d(TAG, "Field ${fieldDef.memoryKey} not available in memory, skipping")
                actions.add(NextAction(
                    action = ActionType.SPEAK_ONLY,
                    targetDescription = fieldDef.uiLabel,
                    voicePrompt = "${fieldDef.uiLabel}这里老白还不清楚，请你自己填一下哦~",
                    explanation = "缺少${fieldDef.uiLabel}信息，提示用户手动填写",
                    riskLevel = RiskLevel.ZERO,
                    source = "form_engine",
                ))
            }
        }

        // Final safety: stop before submit
        val blockedOnPage = if (observation != null) {
            template.blockedTargets.filter { blocked ->
                observation.uiElements.any { it.text.contains(blocked, ignoreCase = true) }
            }
        } else emptyList()

        if (blockedOnPage.isNotEmpty()) {
            val blockedNames = blockedOnPage.joinToString("、")
            actions.add(NextAction(
                action = ActionType.ASK_CONFIRMATION,
                targetDescription = "stop_before_submit",
                voicePrompt = "信息已经填好了，但是老白帮不了您点'${blockedNames}'这个按钮。请您自己检查一遍信息，确认无误后再点提交哦~",
                explanation = "停止在提交前，提示用户自己确认",
                riskLevel = RiskLevel.HIGH,
                source = "form_engine",
            ))
        } else {
            actions.add(NextAction(
                action = ActionType.SPEAK_ONLY,
                targetDescription = "fill_done",
                voicePrompt = "信息已经帮您填好啦，请您检查一下，没问题的话自己点提交哦~",
                explanation = "填写完成，提示用户检查",
                riskLevel = RiskLevel.LOW,
                source = "form_engine",
            ))
        }

        // Initialize fill state
        fillActions = actions
        fillActionIndex = 0
        currentState = FillState(
            templateId = template.templateId,
            templateName = template.displayName,
            totalFields = template.requiredFields.size,
            filledFields = 0,
            isActive = true,
        )

        Log.d(TAG, "Generated ${actions.size} fill actions for template: ${template.templateId}")
        return actions
    }

    /**
     * Get the next action in the fill sequence.
     * Returns null when all actions have been consumed.
     */
    fun getNextAction(): NextAction? {
        if (fillActionIndex >= fillActions.size) return null
        val action = fillActions[fillActionIndex]
        fillActionIndex++

        // Update fill state for TYPE_TEXT actions
        if (action.action == ActionType.TYPE_TEXT) {
            currentState = currentState.copy(
                filledFields = currentState.filledFields + 1,
                currentFieldLabel = action.targetDescription,
            )
        }

        return action
    }

    /**
     * Check if the given element should stop the fill process.
     * Used for real-time safety checks during fill execution.
     *
     * @param elementText The text of the UI element.
     * @param template The active form template.
     * @return true if filling should stop before interacting with this element.
     */
    fun shouldStopForElement(elementText: String, template: FormTemplate): Boolean {
        val lowerText = elementText.lowercase()
        val isBlocked = template.blockedTargets.any { lowerText.contains(it.lowercase()) }

        if (isBlocked) {
            Log.w(TAG, "Blocked target detected: $elementText — stopping fill")
            currentState = currentState.copy(
                stoppedReason = "遇到禁止操作: $elementText",
                isPaused = true,
            )
        }

        return isBlocked
    }

    /**
     * Get the current fill state.
     */
    fun getFillState(): FillState = currentState

    /**
     * Reset the fill state for a new fill operation.
     */
    fun reset() {
        fillActions = emptyList()
        fillActionIndex = 0
        currentState = FillState()
    }

    /**
     * Read a field value from LocalUserMemory.
     * Returns null if the field is not authorized or not stored.
     */
    private fun getMemoryValue(fieldDef: FormFieldDef): String? {
        // Security check: never auto-fill ID card or OTP fields
        if (fieldDef.fieldType == "id_card") {
            Log.w(TAG, "Blocked: ID card field auto-fill for ${fieldDef.uiLabel}")
            return null
        }
        if (fieldDef.memoryKey.contains("phone") && fieldDef.memoryKey.contains("full")) {
            Log.w(TAG, "Blocked: full phone number auto-fill for ${fieldDef.uiLabel}")
            return null
        }

        // For now, use a simple in-memory fallback (the suspend function requires coroutine)
        // In production, this would be called from a coroutine scope
        return try {
            // Use synchronous fallback values for demo
            getLocalFallbackValue(fieldDef.memoryKey)
        } catch (e: Exception) {
            Log.w(TAG, "Failed to read memory for ${fieldDef.memoryKey}", e)
            null
        }
    }

    /**
     * Synchronous fallback to get values from LocalUserMemory state.
     * In a real scenario, beginFill would be a suspend function.
     */
    private fun getLocalFallbackValue(memoryKey: String): String? {
        // The state flow holds cached values loaded during initialization
        return LocalUserMemory.state.value[memoryKey]
    }
}
